// Deprecated compatibility shim.
//
// Client-side video thumbnail capture is intentionally disabled.
// Canonical Media Delivery contract: no hidden <video>, no preload metadata/auto,
// and no page-view derivative generation. Posters/thumbnails are generated by the
// existing background/server workers (gallery-thumbs / post-thumbs / channel-thumbs).
//
// Keep this export temporarily so any stale/branch-only consumer fails safe with
// ZERO media network rather than reintroducing public MP4 egress.
export function ensureVideoThumbs() {
  return undefined;
}
