import React, { useEffect, useMemo, useState } from "react";
import { supabase } from "../../lib/supabase.js";
import { useAuth } from "../../lib/AuthContext.jsx";

const CALIBRATION_REFS = ["posts:136", "posts:53", "posts:976", "posts:904"];
const NAV = [["feed", "זרם מחקר"], ["findings", "ממצאים"], ["sources", "מקורות"], ["review", "לבדיקה"]];
const STATUS = {
  VERIFIED: { label: "מאומת", tone: "ok" }, HELD: { label: "מוחזק לבדיקה", tone: "hold" },
  MISMATCH: { label: "אי־התאמה", tone: "bad" }, NEW: { label: "חדש", tone: "info" }, EXISTING: { label: "קיים", tone: "muted" },
};

function stateOf(row) {
  const d = row?.engine_detail || {};
  if (Array.isArray(d.source_mismatches) && d.source_mismatches.length) return "MISMATCH";
  if (row?.engine_verified === false || d.reason === "COUNTING_CONVENTION_OR_EDITION_UNRESOLVED" || d.status === "NOT_REPRODUCED_UNDER_CURRENT_CONVENTION") return "HELD";
  if (row?.engine_verified === true) return "VERIFIED";
  return row?.status === "candidate" ? "NEW" : "EXISTING";
}
function postId(ref) { const m = /^posts:(\d+)$/.exec(ref || ""); return m ? Number(m[1]) : null; }
function stripHtml(v, max = 220) { const s = String(v || "").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim(); return s.length > max ? `${s.slice(0, max)}…` : s; }
function titleFor(row) {
  if (!row) return "ממצא";
  if (row.source_ref === "posts:136") return "הליך מאומת — 5784";
  if (row.source_ref === "posts:53") return "פסוק 5785 — טענה בהחזקה";
  if (row.source_ref === "posts:976") return "פסוק 358 בכל חומש";
  if (row.source_ref === "posts:904") return "37 × 73 = 2701";
  return row.value != null ? `ממצא ${row.value}` : row.kind;
}
function pretty(v) { return typeof v === "string" ? v : JSON.stringify(v, null, 2); }

const CSS = `
.rv{min-height:100vh;direction:rtl;color:#eaf2ff;background:
radial-gradient(900px 520px at 74% -10%,rgba(46,91,255,.18),transparent 62%),radial-gradient(760px 500px at 6% 15%,rgba(0,212,255,.10),transparent 58%),#050914;
font-family:Arial,sans-serif;padding:14px}.rv *{box-sizing:border-box}.rv button{font:inherit}.rv-shell{max-width:1680px;margin:auto}
.rv-top{display:grid;grid-template-columns:290px 1fr 300px;align-items:center;gap:12px;padding:12px 16px;border:1px solid #19335d;background:rgba(8,16,32,.9);border-radius:20px;box-shadow:0 20px 70px #0008;position:sticky;top:8px;z-index:20;backdrop-filter:blur(18px)}
.rv-brand{display:flex;gap:11px;align-items:center}.rv-logo{width:44px;height:44px;border-radius:15px;display:grid;place-items:center;background:linear-gradient(135deg,#0a2344,#0e4461);border:1px solid #285d82;color:#6ee7ff;font-size:25px;box-shadow:0 0 25px #00cfff20}.rv-brand b{font-size:21px;letter-spacing:.04em}.rv-brand small,.rv-human small{display:block;color:#7890b4;margin-top:2px}
.rv-nav{display:flex;justify-content:center;gap:7px;flex-wrap:wrap}.rv-nav button{color:#a9bad3;background:transparent;border:1px solid transparent;border-radius:12px;padding:9px 13px;cursor:pointer}.rv-nav button.on{color:#fff;background:linear-gradient(180deg,#102c51,#0b1a31);border-color:#244f82;box-shadow:inset 0 -2px #54c9ff}.rv-nav .future{opacity:.42;cursor:default}.rv-human{text-align:left;display:flex;justify-content:flex-start;gap:10px;align-items:center}.rv-avatar{width:42px;height:42px;border-radius:50%;border:1px solid #1fd2d6;display:grid;place-items:center;color:#4df2e7;background:#07303a}
.rv-hero{display:grid;grid-template-columns:1.03fr 1.7fr 1.08fr;gap:12px;margin-top:12px;align-items:start}.rv-panel{background:linear-gradient(180deg,rgba(8,17,34,.96),rgba(5,12,25,.96));border:1px solid #17345d;border-radius:18px;box-shadow:0 16px 46px #0007;overflow:hidden}.rv-panel-title{padding:14px 15px 10px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #112641}.rv-panel-title h3{margin:0;font-size:16px}.rv-live{color:#42e69a;font-size:11px}.rv-feed{padding:10px;display:grid;gap:9px}.rv-stats{display:grid;grid-template-columns:repeat(5,1fr);gap:6px;margin-bottom:8px}.rv-stat{border:1px solid #1a3152;background:#091426;border-radius:12px;padding:8px;text-align:center}.rv-stat strong{font-size:20px;display:block}.rv-stat small{color:#7185a6;font-size:10px}.rv-feed-card{width:100%;text-align:right;color:#dfeaff;background:#081427;border:1px solid #183257;border-right:3px solid #466483;border-radius:13px;padding:11px;cursor:pointer;transition:.18s}.rv-feed-card:hover,.rv-feed-card.on{transform:translateY(-1px);border-color:#3c6da4;background:#0b1930}.rv-feed-card.bad{border-right-color:#ff626b}.rv-feed-card.hold{border-right-color:#efa936}.rv-feed-card.ok{border-right-color:#3be18b}.rv-feed-head{display:flex;justify-content:space-between;gap:8px;align-items:center}.rv-feed-card h4{margin:8px 0 5px;font-size:15px}.rv-feed-card p{margin:0;color:#8396b4;font-size:11px;line-height:1.55}.rv-chip{display:inline-flex;align-items:center;gap:5px;border-radius:999px;padding:4px 8px;border:1px solid #29425f;color:#a9bad3;background:#08101e;font-size:10px;font-weight:800}.rv-chip.bad{border-color:#7c3038;color:#ff868c;background:#261014}.rv-chip.hold{border-color:#79541e;color:#ffc25c;background:#241a0c}.rv-chip.ok{border-color:#185e42;color:#6df0ab;background:#08241a}.rv-chip.info{border-color:#265c9d;color:#80bcff;background:#0b1c36}
.rv-main{min-height:680px}.rv-main-head{padding:15px 18px;border-bottom:1px solid #17304f}.rv-kicker{color:#6e8caf;font-size:11px;letter-spacing:.08em}.rv-main h1{font-size:27px;margin:8px 0 4px}.rv-sub{color:#91a4c0;font-size:12px;line-height:1.65}.rv-meta{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;padding:12px 15px}.rv-meta>div{border:1px solid #173251;background:#081427;border-radius:11px;padding:9px}.rv-meta small{color:#6e83a4;display:block;font-size:10px}.rv-meta b{font-size:12px;margin-top:5px;display:block}.rv-focus{margin:0 15px 12px;border:1px solid #18375e;background:linear-gradient(180deg,#07172b,#06111f);border-radius:16px;padding:15px}.rv-sequence{display:flex;align-items:center;justify-content:center;gap:18px;flex-wrap:wrap;padding:10px}.rv-token{text-align:center;min-width:75px}.rv-token b{font-size:31px;display:block}.rv-token small{color:#90a6c5}.rv-plus{font-size:25px;color:#6684a7}.rv-seqbox{font-size:34px;letter-spacing:.14em;font-family:monospace;border:1px solid #5b354c;background:#170d18;padding:10px 14px;border-radius:13px;direction:ltr}.rv-seqbox em{font-style:normal;color:#ff888f;background:#4f1620;padding:1px 4px;border-radius:5px;box-shadow:0 0 20px #ff526855}.rv-grid2{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:0 15px 12px}.rv-card{border:1px solid #173251;background:#081427;border-radius:14px;padding:13px}.rv-card h4{margin:0 0 9px;font-size:13px}.rv-compare{display:grid;grid-template-columns:1fr 1fr;gap:8px}.rv-compare>div{padding:10px;border-radius:10px;background:#07101d;border:1px solid #1d3350}.rv-compare .source{border-color:#6b3535}.rv-compare .canon{border-color:#1f654c}.rv-compare strong{display:block;margin-bottom:6px}.rv-pre{white-space:pre-wrap;word-break:break-word;font:11px/1.55 monospace;color:#9fb0c8;margin:0}.rv-why{margin:0 15px 15px;padding:14px;border-top:1px solid #142b49}.rv-chain{display:grid;grid-template-columns:repeat(5,1fr);gap:9px;margin-top:10px}.rv-step{text-align:center;border:1px solid #1b3a61;background:#071525;border-radius:13px;padding:11px}.rv-step .ico{width:38px;height:38px;border-radius:50%;display:grid;place-items:center;margin:0 auto 7px;background:#0c2744;border:1px solid #27557e;color:#70dfff;font-size:19px}.rv-step b{font-size:11px;display:block}.rv-step small{font-size:9px;color:#7288a7;display:block;margin-top:5px;line-height:1.4}
.rv-side{padding-bottom:10px}.rv-graph{height:330px;position:relative;margin:10px;border:1px solid #173456;border-radius:15px;background:radial-gradient(circle at center,#12223b,#050d19 67%);overflow:hidden}.rv-node{position:absolute;min-width:82px;max-width:115px;padding:8px 10px;border-radius:13px;border:1px solid #31557a;background:#09172a;text-align:center;font-size:11px;box-shadow:0 8px 20px #0008}.rv-node.center{left:50%;top:48%;transform:translate(-50%,-50%);width:104px;height:104px;border-radius:50%;display:grid;place-items:center;font-size:27px;font-weight:900;border-color:#ff6870;background:radial-gradient(circle,#3b1720,#190a0f);box-shadow:0 0 35px #ff4d5f30}.rv-node.n1{top:11%;left:38%}.rv-node.n2{top:27%;right:6%}.rv-node.n3{bottom:12%;right:11%}.rv-node.n4{bottom:8%;left:9%}.rv-node.n5{top:29%;left:4%}.rv-lines{position:absolute;inset:0;width:100%;height:100%;opacity:.65}.rv-review{display:grid;gap:7px;padding:10px}.rv-review-row{display:flex;gap:7px;justify-content:space-between;align-items:center;border:1px solid #17304d;background:#071321;border-radius:10px;padding:9px;font-size:11px}.rv-bottom{display:grid;grid-template-columns:1.35fr 1.4fr 1.1fr;gap:12px;margin-top:12px}.rv-bottom .rv-panel{padding:14px;min-height:150px}.rv-els{display:grid;grid-template-columns:1fr 1fr;gap:8px}.rv-pair{font-size:11px;color:#91a4be}.rv-pair b{display:block;color:#dce9fb;margin-top:3px}.rv-methods{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.rv-method{width:74px;text-align:center;padding:9px;border:1px solid #193653;border-radius:12px;background:#071522}.rv-method span{font-size:20px;display:block}.rv-method small{color:#8ea2bd}.rv-online{display:flex;justify-content:space-between;padding:5px 0;font-size:11px}.rv-online i{font-style:normal;color:#4be69b}.rv-note{color:#8296b4;font-size:11px;line-height:1.7}.rv-preview{color:#7f92ad;border:1px dashed #2a4665;background:#07111e;border-radius:10px;padding:8px;margin-top:8px;font-size:10px}
@media(max-width:1180px){.rv-top{grid-template-columns:1fr}.rv-human,.rv-brand{justify-content:center;text-align:center}.rv-hero{grid-template-columns:1fr 1.5fr}.rv-side{grid-column:1/-1}.rv-bottom{grid-template-columns:1fr 1fr}.rv-bottom .rv-panel:last-child{grid-column:1/-1}}
@media(max-width:760px){.rv{padding:7px}.rv-top{position:static;border-radius:14px}.rv-hero,.rv-bottom,.rv-grid2{grid-template-columns:1fr}.rv-main{grid-row:1}.rv-feed-col{grid-row:2}.rv-side{grid-row:3}.rv-meta{grid-template-columns:1fr 1fr}.rv-stats{grid-template-columns:repeat(3,1fr)}.rv-chain{grid-template-columns:1fr 1fr}.rv-compare{grid-template-columns:1fr}.rv-seqbox{font-size:25px}.rv-main h1{font-size:23px}}
`;

function Chip({ state, children }) { const s = STATUS[state] || STATUS.EXISTING; return <span className={`rv-chip ${s.tone}`}>{children || s.label}</span>; }
function Stat({ n, label }) { return <div className="rv-stat"><strong>{n}</strong><small>{label}</small></div>; }

export default function ResearchViewerV0Page() {
  const { loading: authLoading, isAdmin } = useAuth();
  const [tab, setTab] = useState("feed"); const [rows, setRows] = useState([]); const [posts, setPosts] = useState({});
  const [els, setEls] = useState(null); const [nodes, setNodes] = useState([]); const [edges, setEdges] = useState([]);
  const [selectedId, setSelectedId] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");

  useEffect(() => {
    if (authLoading || !isAdmin) return; let alive = true;
    (async () => { setLoading(true); setError(""); try {
      const fields = "id,created_at,kind,statement,terms,value,relates,source,source_ref,contributor,confidence,engine_verified,engine_detail,status,privacy_scope,promoted_node_id";
      const { data: ro, error: roErr } = await supabase.from("research_objects").select(fields).in("source_ref", CALIBRATION_REFS).order("created_at", { ascending: false }); if (roErr) throw roErr;
      const findings = ro || []; const ids = [...new Set(findings.map(r => postId(r.source_ref)).filter(Boolean))]; let postMap = {};
      if (ids.length) { const { data: ps, error: pErr } = await supabase.from("posts").select("id,title,slug,content,excerpt,source,created_at").in("id", ids); if (pErr) throw pErr; postMap = Object.fromEntries((ps || []).map(p => [p.id, p])); }
      const { data: er, error: eErr } = await supabase.from("els_records").select("id,title,search_term,skip_distance,primary_number,visibility,status,source,corpus_id,start_index,engine_detail,slug").eq("search_term", "משיח טבת עשירי").limit(1).maybeSingle(); if (eErr) throw eErr;
      const labels = [...new Set(findings.flatMap(r => [...(r.terms || []), r.value != null ? String(r.value) : null]).filter(Boolean))].slice(0, 80); let ns = [];
      if (labels.length) { const { data: nd, error: nErr } = await supabase.from("nodes").select("id,type,label,description").in("label", labels).limit(120); if (nErr) throw nErr; ns = nd || []; }
      let es = []; if (ns.length) { const idsCsv = ns.map(n => n.id).join(","); const { data: ed, error: edgeErr } = await supabase.from("edges").select("id,from_node,to_node,relation_type,weight,metadata").or(`from_node.in.(${idsCsv}),to_node.in.(${idsCsv})`).limit(120); if (edgeErr) throw edgeErr; es = ed || []; }
      if (!alive) return; setRows(findings); setPosts(postMap); setEls(er || null); setNodes(ns); setEdges(es); setSelectedId(findings.find(r => r.source_ref === "posts:136")?.id || findings[0]?.id || null);
    } catch (e) { if (alive) setError(e?.message || String(e)); } finally { if (alive) setLoading(false); } })(); return () => { alive = false; };
  }, [authLoading, isAdmin]);

  const selected = rows.find(r => r.id === selectedId) || rows[0] || null; const d = selected?.engine_detail || {}; const selectedPost = selected ? posts[postId(selected.source_ref)] : null;
  const verified = rows.filter(r => stateOf(r) === "VERIFIED").length, held = rows.filter(r => stateOf(r) === "HELD").length, mismatch = rows.filter(r => stateOf(r) === "MISMATCH").length;
  const selectedNodeIds = new Set(nodes.filter(n => selected && ((selected.terms || []).includes(n.label) || String(selected.value) === n.label)).map(n => n.id)); const relatedEdges = edges.filter(e => selectedNodeIds.has(e.from_node) || selectedNodeIds.has(e.to_node));
  const feedRows = useMemo(() => [...rows].sort((a,b) => ({MISMATCH:0,HELD:1,VERIFIED:2}[stateOf(a)] ?? 3) - ({MISMATCH:0,HELD:1,VERIFIED:2}[stateOf(b)] ?? 3)), [rows]);

  if (authLoading) return <main className="rv"><style>{CSS}</style><div className="rv-shell">טוען הרשאות…</div></main>;
  if (!isAdmin) return <main className="rv"><style>{CSS}</style><div className="rv-shell"><div className="rv-panel" style={{maxWidth:620,margin:"80px auto",padding:30,textAlign:"center"}}><h2>Research Viewer v0</h2><p>פנימי · אדמין בלבד.</p></div></div></main>;

  const result = d.result || {}; const seq = result.sequence || ""; const sourceClaim = d.source_claim || d.source_mismatches || selected?.statement; const canonical = d.canonical_result || d.canonical_book358 || d.result || d;
  const sourceTitle = selectedPost?.title || selected?.source_ref || "מקור";
  return <main className="rv"><style>{CSS}</style><div className="rv-shell">
    <header className="rv-top"><div className="rv-brand"><div className="rv-logo">♜</div><div><b>SOD1820</b><small>RESEARCH OS · Future Product Preview</small></div></div>
      <nav className="rv-nav">{NAV.map(([k,v]) => <button className={tab===k?"on":""} key={k} onClick={()=>setTab(k)}>{k==="feed"?"⌁ ":k==="findings"?"◇ ":k==="sources"?"▤ ":"☆ "}{v}</button>)}<button className="future" title="Preview only">מפת קשרים · Preview</button><button className="future" title="Preview only">ציר זמן · Preview</button></nav>
      <div className="rv-human"><div><b>צוריאל</b><small>Human Gate</small></div><div className="rv-avatar">✦</div></div></header>

    {error && <div className="rv-panel" style={{marginTop:12,padding:14,color:"#ff9298"}}>Live read failed: {error}</div>}
    {loading ? <div className="rv-panel" style={{marginTop:12,padding:30,textAlign:"center"}}>טוען את מערכת המחקר החיה…</div> : <>
    <section className="rv-hero">
      <aside className="rv-panel rv-feed-col"><div className="rv-panel-title"><h3>זרם המחקר <span className="rv-live">● LIVE</span></h3><span>⌕</span></div><div className="rv-feed">
        <div className="rv-stats"><Stat n={rows.length} label="ממצאים"/><Stat n={verified} label="מאומת"/><Stat n={held} label="Held"/><Stat n={mismatch} label="Mismatch"/><Stat n={els?1:0} label="ELS"/></div>
        {feedRows.map(r => { const st=stateOf(r), p=posts[postId(r.source_ref)]; return <button key={r.id} className={`rv-feed-card ${STATUS[st].tone} ${selected?.id===r.id?"on":""}`} onClick={()=>{setSelectedId(r.id);setTab("findings")}}><div className="rv-feed-head"><Chip state={st}/><span className="rv-chip">{r.source_ref}</span></div><h4>{titleFor(r)}</h4><p>{stripHtml(p?.excerpt || r.statement,145)}</p></button>})}
        {els && <div className="rv-feed-card ok"><div className="rv-feed-head"><Chip state="VERIFIED">SOURCE-NATIVE</Chip><span className="rv-chip">ELS</span></div><h4>משיח טבת עשירי · skip {els.skip_distance}</h4><p>רשומה קיימת, published, הועשרה במנוע הקנוני ללא כפילות.</p></div>}
      </div></aside>

      <section className="rv-panel rv-main"><div className="rv-main-head"><div className="rv-feed-head"><div><div className="rv-kicker">ממצא נבחר · {selected?.source_ref}</div><h1>{titleFor(selected)}</h1></div><Chip state={stateOf(selected)}/></div><div className="rv-sub">{selected?.statement}</div></div>
        <div className="rv-meta"><div><small>סוג</small><b>{selected?.kind || "—"}</b></div><div><small>שיטה / מנוע</small><b>{d.engine || "ללא אימות מנוע"}</b></div><div><small>פרטיות</small><b>{selected?.privacy_scope || "—"}</b></div><div><small>אימות</small><b>{selected?.engine_verified===true?"ENGINE VERIFIED":selected?.engine_verified===false?"NOT VERIFIED":"—"}</b></div><div><small>סטטוס אמת</small><b>{STATUS[stateOf(selected)]?.label}</b></div></div>

        {selected?.source_ref === "posts:136" ? <div className="rv-focus"><div className="rv-kicker">רצף הגימטריה שנוצר</div><div className="rv-sequence"><div className="rv-token"><small>אנוש</small><b>357</b></div><span className="rv-plus">+</span><div className="rv-token"><small>אז</small><b>8</b></div><span className="rv-plus">+</span><div className="rv-token"><small>הוחל</small><b>49</b></div><span className="rv-plus">←</span><div className="rv-seqbox">35<em>5784</em>9</div></div></div> : <div className="rv-focus"><div className="rv-kicker">ערך / ממצא</div><div style={{fontSize:42,fontWeight:900,marginTop:8}}>{selected?.value ?? "—"}</div></div>}

        <div className="rv-grid2"><div className="rv-card"><h4>המקור המקורי</h4><div className="rv-kicker">{sourceTitle}</div><p className="rv-note">{stripHtml(selectedPost?.excerpt || selectedPost?.content || selected?.statement,300)}</p></div><div className="rv-card"><h4>פרטי מנוע / Procedure</h4>{Array.isArray(d.procedure)?d.procedure.map((x,i)=><div className="rv-pair" key={x}>{i+1}. <b style={{display:"inline"}}>{x}</b></div>):<pre className="rv-pre">{pretty(d.engine || d.arithmetic || "אין procedure מפורש")}</pre>}</div></div>

        {(stateOf(selected)==="HELD" || stateOf(selected)==="MISMATCH") && <div className="rv-grid2" style={{gridTemplateColumns:"1fr"}}><div className="rv-card"><h4 style={{color:"#ff8c92"}}>אי־התאמה / HOLD — המקור נשמר, האמת לא משוכתבת</h4><div className="rv-compare"><div className="source"><strong>טענת המקור</strong><pre className="rv-pre">{pretty(sourceClaim)}</pre></div><div className="canon"><strong>תוצאת הקורפוס / המנוע</strong><pre className="rv-pre">{pretty(canonical)}</pre></div></div><p className="rv-note">סיבה אפשרית: מהדורה, tokenization, segmentation או שיטת ספירה שטרם שוחזרה.</p></div></div>}

        <div className="rv-why"><h4 style={{margin:0}}>למה אני רואה את זה?</h4><div className="rv-chain">{[["▤","מקור",selected?.source_ref],["⇩","חילוץ",selected?.kind],["⌗","שיטה",d.engine||"procedure"],["✓","אימות מנוע",selected?.engine_verified===true?"מאומת":"לא מאומת"],["◎","ממצא",STATUS[stateOf(selected)]?.label]].map(([ico,a,b])=><div className="rv-step" key={a}><div className="ico">{ico}</div><b>{a}</b><small>{String(b||"—")}</small></div>)}</div></div>
      </section>

      <aside className="rv-panel rv-side"><div className="rv-panel-title"><h3>מפת הקשרים</h3><span className="rv-kicker">One Tree · live identities</span></div><div className="rv-graph"><svg className="rv-lines" viewBox="0 0 400 330" preserveAspectRatio="none"><g stroke="#527fab" strokeWidth="1"><line x1="200" y1="160" x2="200" y2="55"/><line x1="205" y1="165" x2="340" y2="100"/><line x1="205" y1="170" x2="325" y2="275"/><line x1="195" y1="170" x2="75" y2="280"/><line x1="195" y1="160" x2="55" y2="105"/></g></svg><div className="rv-node center">{selected?.value ?? "?"}</div><div className="rv-node n1">{selected?.source_ref}<br/><small>מקור</small></div><div className="rv-node n2">{(selected?.terms||[])[0] || "שיטה"}<br/><small>זהות</small></div><div className="rv-node n3">{d.engine?"מנוע":"Procedure"}<br/><small>{d.engine?"verified path":"research"}</small></div><div className="rv-node n4">{selectedPost?`פוסט ${postId(selected.source_ref)}`:"Source"}<br/><small>provenance</small></div><div className="rv-node n5">{relatedEdges.length} קשרים<br/><small>live edges</small></div></div><div className="rv-preview">Preview חזותי בלבד. אין Graph Store חדש; המסך משתמש ב־nodes/edges החיים.</div>
        <div className="rv-panel-title"><h3>מחכה לצוריאל</h3><span>{rows.filter(r=>stateOf(r)!=="VERIFIED").length}</span></div><div className="rv-review">{rows.filter(r=>stateOf(r)!=="VERIFIED").map(r=><button className="rv-review-row" key={r.id} onClick={()=>setSelectedId(r.id)}><span>{titleFor(r)}</span><Chip state={stateOf(r)}/></button>)}{els&&<div className="rv-review-row"><span>ELS · משיח טבת עשירי</span><Chip state="VERIFIED">SOURCE-NATIVE</Chip></div>}</div>
      </aside>
    </section>

    <section className="rv-bottom"><div className="rv-panel"><h3 style={{marginTop:0}}>מקור־טבעי · ELS</h3>{els?<div className="rv-els"><div className="rv-pair">ביטוי<b>{els.search_term}</b></div><div className="rv-pair">skip<b>{els.skip_distance}</b></div><div className="rv-pair">status<b style={{color:"#4fe39a"}}>{els.status}</b></div><div className="rv-pair">engine<b>{els.engine_detail?.engine || "—"}</b></div><div className="rv-pair">corpus_id<b>{els.corpus_id}</b></div><div className="rv-pair">start_index<b>{els.start_index}</b></div></div>:<div className="rv-note">אין רשומת ELS.</div>}</div>
      <div className="rv-panel"><h3 style={{marginTop:0}}>שיטות פעילות בממצא</h3><div className="rv-methods"><div className="rv-method"><span>✂</span><small>רגיל</small></div><div className="rv-method"><span>⌘</span><small>גימטריה</small></div><div className="rv-method"><span>⌗</span><small>רצף ספרות</small></div><div className="rv-method"><span>ELS</span><small>דילוגים</small></div><div className="rv-method"><span>↔</span><small>קשרים</small></div></div><div className="rv-preview">Future-capability preview: שיטות נוספות יוצגו כאן רק כשהן חיות/מאומתות, לא כנתונים מומצאים.</div></div>
      <div className="rv-panel"><h3 style={{marginTop:0}}>סטטוס מערכת</h3>{[["Research OS",true],["One Tree",true],["Engine verification",true],["Human Gate",true]].map(([a,on])=><div className="rv-online" key={a}><span>{a}</span><i>{on?"● ONLINE":"OFF"}</i></div>)}<p className="rv-note">כל מה שמוצג כ־LIVE מגיע מהמערכת החיה. יכולות עתידיות מסומנות Preview ולא מקודמות לאמת.</p></div></section>
    </>}</div></main>;
}
