-- Read-only application-schema snapshot for isolated F01/F02 acceptance.
-- No application rows, auth identities, vault values, storage objects or cron jobs.
-- Three credential-bearing external integrations are replaced with offline errors.
with app as (
  select c.*,n.nspname,format('%I.%I',n.nspname,c.relname) as identity
  from pg_class c join pg_namespace n on n.oid=c.relnamespace
  where n.nspname in ('public','research','private')
    and not exists(select 1 from pg_depend d where d.classid='pg_class'::regclass and d.objid=c.oid and d.deptype='e')
), funcs as (
  select p.*,n.nspname,p.oid::regprocedure::text as identity
  from pg_proc p join pg_namespace n on n.oid=p.pronamespace
  where n.nspname in ('public','research','private') and p.prokind in ('f','p')
    and not exists(select 1 from pg_depend d where d.classid='pg_proc'::regclass and d.objid=p.oid and d.deptype='e')
), records as (
  select 'schema' as kind, nspname as identity,
    format('create schema if not exists %I;',nspname) as ddl
    from pg_namespace where nspname in ('public','research','private')
  union all
  select 'enum',format('%I.%I',n.nspname,t.typname),
    format('create type %I.%I as enum (%s);',n.nspname,t.typname,
      (select string_agg(quote_literal(e.enumlabel),',' order by e.enumsortorder) from pg_enum e where e.enumtypid=t.oid))
    from pg_type t join pg_namespace n on n.oid=t.typnamespace
    where n.nspname in ('public','research','private') and t.typtype='e'
  union all
  select 'sequence',a.identity,
    format('create sequence %s as %s increment %s minvalue %s maxvalue %s start %s cache %s %s;',
      a.identity,format_type(s.seqtypid,null),s.seqincrement,s.seqmin,s.seqmax,s.seqstart,s.seqcache,
      case when s.seqcycle then 'cycle' else 'no cycle' end)
    from app a join pg_sequence s on s.seqrelid=a.oid
  union all
  select 'table',a.identity,
    case when a.relispartition then
      format('create table %s partition of %s %s;',a.identity,
        (select i.inhparent::regclass::text from pg_inherits i where i.inhrelid=a.oid),pg_get_expr(a.relpartbound,a.oid))
    else format('create table %s (%s)%s;',a.identity,
      (select string_agg(format('%I %s%s%s%s',c.attname,format_type(c.atttypid,c.atttypmod),
        case when c.attidentity='a' then ' generated always as identity' when c.attidentity='d' then ' generated by default as identity' else '' end,
        case when c.attgenerated<>'' then ' generated always as ('||pg_get_expr(d.adbin,d.adrelid)||') stored' else '' end,
        case when c.attnotnull then ' not null' else '' end),',' order by c.attnum)
       from pg_attribute c left join pg_attrdef d on d.adrelid=c.attrelid and d.adnum=c.attnum
       where c.attrelid=a.oid and c.attnum>0 and not c.attisdropped),
      case when a.relkind='p' then ' partition by '||pg_get_partkeydef(a.oid) else '' end) end
    from app a where a.relkind in ('r','p')
  union all
  select 'default',a.identity||'.'||c.attname,
    format('alter table %s alter column %I set default %s;',a.identity,c.attname,pg_get_expr(d.adbin,d.adrelid))
    from app a join pg_attribute c on c.attrelid=a.oid join pg_attrdef d on d.adrelid=c.attrelid and d.adnum=c.attnum
    where a.relkind in ('r','p') and c.attgenerated='' and c.attidentity=''
  union all
  select 'function',f.identity,
    case when f.proname in ('social_admin','sod_fb_call','video_translate') then
      format('create or replace function %I.%I(%s) returns %s language plpgsql %s as $offline$ begin raise exception ''OFFLINE_EXTERNAL_INTEGRATION''; end; $offline$;',
        f.nspname,f.proname,pg_get_function_arguments(f.oid),pg_get_function_result(f.oid),
        case when f.prosecdef then 'security definer' else 'security invoker' end)
      else pg_get_functiondef(f.oid) end
    from funcs f
  union all
  select 'view',a.identity,
    format('create %sview %s%s as %s%s;',case when a.relkind='m' then 'materialized ' else '' end,a.identity,
      case when a.reloptions is null then '' else ' with ('||array_to_string(a.reloptions,',')||')' end,
      rtrim(pg_get_viewdef(a.oid,true),';'),case when a.relkind='m' then ' with no data' else '' end)
    from app a where a.relkind in ('v','m')
  union all
  select 'constraint',a.identity||'.'||c.conname,
    format('alter table %s add constraint %I %s;',a.identity,c.conname,pg_get_constraintdef(c.oid,true))
    from app a join pg_constraint c on c.conrelid=a.oid
    where c.contype in ('p','u','c','f','x') and c.conparentid=0
  union all
  select 'index',format('%I.%I',a.nspname,i.relname),pg_get_indexdef(i.oid)||';'
    from app a join pg_index x on x.indrelid=a.oid join pg_class i on i.oid=x.indexrelid
    where not exists(select 1 from pg_constraint c where c.conindid=i.oid)
  union all
  select 'rls',a.identity,
    format('alter table %s %s row level security; alter table %s %s row level security;',a.identity,
      case when a.relrowsecurity then 'enable' else 'disable' end,a.identity,
      case when a.relforcerowsecurity then 'force' else 'no force' end)
    from app a where a.relkind in ('r','p')
  union all
  select 'policy',format('%I.%I.%I',p.schemaname,p.tablename,p.policyname),
    format('create policy %I on %I.%I as %s for %s to %s%s%s;',p.policyname,p.schemaname,p.tablename,
      p.permissive,p.cmd,(select string_agg(case when r='public' then 'public' else quote_ident(r) end,',') from unnest(p.roles::text[]) r),
      case when p.qual is null then '' else ' using ('||p.qual||')' end,
      case when p.with_check is null then '' else ' with check ('||p.with_check||')' end)
    from pg_policies p where p.schemaname in ('public','research','private') or (p.schemaname='storage' and p.tablename='objects')
  union all
  select 'trigger',format('%I.%I.%I',n.nspname,c.relname,t.tgname),pg_get_triggerdef(t.oid,true)||';'
    from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace
    where not t.tgisinternal and (n.nspname in ('public','research','private') or (n.nspname='auth' and c.relname='users'))
  union all
  select 'table_grant',a.identity||':'||coalesce(r.rolname,'public')||':'||x.privilege_type,
    format('grant %s on %s %s to %s%s;',x.privilege_type,case when a.relkind='S' then 'sequence' else 'table' end,
      a.identity,case when x.grantee=0 then 'public' else quote_ident(r.rolname) end,
      case when x.is_grantable then ' with grant option' else '' end)
    from app a cross join lateral aclexplode(coalesce(a.relacl,acldefault(case when a.relkind='S' then 'S'::"char" else 'r'::"char" end,a.relowner))) x
    left join pg_roles r on r.oid=x.grantee
    where a.relkind in ('r','p','v','m','S')
  union all
  select 'column_grant',a.identity||'.'||c.attname||':'||coalesce(r.rolname,'public')||':'||x.privilege_type,
    format('grant %s (%I) on table %s to %s%s;',x.privilege_type,c.attname,a.identity,
      case when x.grantee=0 then 'public' else quote_ident(r.rolname) end,
      case when x.is_grantable then ' with grant option' else '' end)
    from app a join pg_attribute c on c.attrelid=a.oid cross join lateral aclexplode(c.attacl) x
    left join pg_roles r on r.oid=x.grantee where c.attnum>0 and not c.attisdropped
  union all
  select 'function_grant',f.identity||':'||coalesce(r.rolname,'public'),
    format('grant execute on %s %I.%I(%s) to %s%s;',case when f.prokind='p' then 'procedure' else 'function' end,
      f.nspname,f.proname,pg_get_function_identity_arguments(f.oid),
      case when x.grantee=0 then 'public' else quote_ident(r.rolname) end,
      case when x.is_grantable then ' with grant option' else '' end)
    from funcs f cross join lateral aclexplode(coalesce(f.proacl,acldefault('f',f.proowner))) x
    left join pg_roles r on r.oid=x.grantee
)
select kind,identity,ddl from records order by kind,identity;
