-- ENGLISH_METHOD_IDENTITIES_V1
-- EXTEND_EXISTING under canonical_methods_registry_law v4.
-- Identity registration only. DO NOT infer activation/execution/scanning from these rows.
-- Human Gate direction locked 2026-09-11: English/Latin methods belong in the single
-- canonical gematria_methods lifecycle; no parallel English-method store.
--
-- This migration intentionally registers only the four English methods already source-attested
-- by approved live language_links and implemented as local capability evidence in
-- src/lib/englishGematria.js. Agrippa/Latin remains deferred until a dedicated source/provenance
-- pass because it is not yet represented in approved live language_links.
--
-- FAIL-CLOSED invariants for every inserted row:
--   active=false · in_engine=false · scannable=false · function=NULL
--   execution_kind='unimplemented' · no db_column · no operator
-- Applying this migration DOES NOT make any English calculation authoritative SOD1820 output.

insert into public.gematria_methods (
  method_key,
  display_label,
  category,
  sub,
  soul,
  db_column,
  in_engine,
  function,
  active,
  deterministic,
  source_of_truth,
  required_entitlement,
  input_schema,
  output_schema,
  token_cost,
  version,
  mathematical_family,
  order_sensitive,
  word_boundary_sensitive,
  per_word_reset,
  full_phrase_continuation,
  final_letter_sensitive,
  whitespace_normalization,
  punctuation_normalization,
  derived_from,
  dependency_rules,
  dependency_version,
  scannable,
  execution_kind,
  operator,
  dependency_versions
)
values
(
  'en_ordinal',
  'English Ordinal',
  'base',
  'SOURCE-ATTESTED ENGLISH METHOD IDENTITY · registered only · canonical engine implementation pending',
  null,
  null,
  false,
  null,
  false,
  true,
  'Human Gate ZURIEL 2026-09-11; canonical_methods_registry_law v4. Source-attested in approved live language_links: English Ordinal appears in 2 approved shared_value bridges, both human_verified=true and evidence_level=strong. Existing src/lib/englishGematria.js contains a deterministic client-side capability implementation, but that code is NOT authoritative engine truth. Register identity now; canonical engine implementation, independent verification, activation and scanning remain separate future gates.',
  'public',
  '{"kind":"text","lang":"en","script":"Latin","formula_status":"capability_evidence_not_engine_verified"}'::jsonb,
  '{"type":"integer","status":"registered_unimplemented"}'::jsonb,
  0,
  1,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  '[]'::jsonb,
  1,
  false,
  'unimplemented',
  null,
  '{}'::jsonb
),
(
  'en_full_reduction',
  'Full Reduction',
  'base',
  'SOURCE-ATTESTED ENGLISH METHOD IDENTITY · registered only · canonical engine implementation pending',
  null,
  null,
  false,
  null,
  false,
  true,
  'Human Gate ZURIEL 2026-09-11; canonical_methods_registry_law v4. Source-attested in approved live language_links: Full Reduction appears in 1 approved shared_value bridge, human_verified=true and evidence_level=strong. Existing src/lib/englishGematria.js contains a deterministic client-side capability implementation, but that code is NOT authoritative engine truth. Register identity now; canonical engine implementation, independent verification, activation and scanning remain separate future gates.',
  'public',
  '{"kind":"text","lang":"en","script":"Latin","formula_status":"capability_evidence_not_engine_verified"}'::jsonb,
  '{"type":"integer","status":"registered_unimplemented"}'::jsonb,
  0,
  1,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  '[]'::jsonb,
  1,
  false,
  'unimplemented',
  null,
  '{}'::jsonb
),
(
  'en_reverse_ordinal',
  'Reverse Ordinal',
  'base',
  'SOURCE-ATTESTED ENGLISH METHOD IDENTITY · registered only · canonical engine implementation pending',
  null,
  null,
  false,
  null,
  false,
  true,
  'Human Gate ZURIEL 2026-09-11; canonical_methods_registry_law v4. Source-attested in approved live language_links: Reverse Ordinal appears in 2 approved shared_value bridges, both human_verified=true and evidence_level=strong. Existing src/lib/englishGematria.js contains a deterministic client-side capability implementation, but that code is NOT authoritative engine truth. Register identity now; canonical engine implementation, independent verification, activation and scanning remain separate future gates.',
  'public',
  '{"kind":"text","lang":"en","script":"Latin","formula_status":"capability_evidence_not_engine_verified"}'::jsonb,
  '{"type":"integer","status":"registered_unimplemented"}'::jsonb,
  0,
  1,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  '[]'::jsonb,
  1,
  false,
  'unimplemented',
  null,
  '{}'::jsonb
),
(
  'en_reverse_reduction',
  'Reverse Reduction',
  'base',
  'SOURCE-ATTESTED ENGLISH METHOD IDENTITY · registered only · canonical engine implementation pending',
  null,
  null,
  false,
  null,
  false,
  true,
  'Human Gate ZURIEL 2026-09-11; canonical_methods_registry_law v4. Source-attested in approved live language_links: Reverse Reduction appears in 2 approved shared_value bridges; 1 is human_verified=true and evidence_level=medium, so the method identity is preserved but no strength/canonicality inference is made from bridge confidence. Existing src/lib/englishGematria.js contains a deterministic client-side capability implementation, but that code is NOT authoritative engine truth. Register identity now; canonical engine implementation, independent verification, activation and scanning remain separate future gates.',
  'public',
  '{"kind":"text","lang":"en","script":"Latin","formula_status":"capability_evidence_not_engine_verified"}'::jsonb,
  '{"type":"integer","status":"registered_unimplemented"}'::jsonb,
  0,
  1,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  '[]'::jsonb,
  1,
  false,
  'unimplemented',
  null,
  '{}'::jsonb
)
on conflict (method_key) do nothing;
